server:
  port: 9090
spring:
  application:
    name: msvc_course
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${_HOST}:5432/cursobd
    username: ${POSTGRE_USER}
    password: ${POSTGRE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # Las siguientes 2 lineas estan porque ahun no esta configurado el microserviceConfig
  config:
    import: optional:configserver:http://${_HOST}:8888
eureka:
  instance:
    hostname: ${_HOST}
  client:
    service-url:
      defaultZone: http://${_HOST}:8761/eureka
